# Generated by Django 2.1.1 on 2018-12-30 06:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181230_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogcontent',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
