# Generated by Django 2.1.1 on 2019-01-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181230_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtype',
            options={'ordering': ['-last_updated_time']},
        ),
        migrations.AddField(
            model_name='blogtype',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
