# Generated by Django 2.1.1 on 2019-01-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190107_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtype',
            options={},
        ),
    ]
