# Generated by Django 2.1.1 on 2019-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190114_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
